# This is the name of your Pages project. It should match what's in the Cloudflare dashboard.
name = "gemini2-5pro"

# This tells Cloudflare Pages where your static site assets are.
# Since your index.html, js/, styles/ are in the root of your repository and you don't have a separate build step for static assets,
# use "." to indicate the root directory.
pages_build_output_dir = "."

# It's good practice to set a compatibility date. Use a recent one.
compatibility_date = "2024-05-16" # You can update this to the current date

# [[pages.functions]] block TEMPORARILY REMOVED to isolate parsing issues
# We will add back the nodejs_compat configuration once the file is parsed correctly.

# bindings = { YOUR_KV_NAMESPACE = { binding = "YOUR_KV_NAMESPACE" } } # 如果您使用KV等绑定，在这里取消注释并配置
# nodejs_compat = true # 有些旧版本的Wrangler可能使用这种方式，但 flags 是目前推荐的 