name = "Gemini2.5Pro" # 您可以根据Cloudflare项目名调整
compatibility_date = "2024-01-01" # 使用一个稍微旧一点但仍然现代的日期

[[pages.functions]]
# bindings = { YOUR_KV_NAMESPACE = { binding = "YOUR_KV_NAMESPACE" } } # 如果您使用KV等绑定，在这里取消注释并配置
compatibility_flags = [ "nodejs_compat" ] # 尝试使用最基础的 nodejs_compat
# nodejs_compat = true # 有些旧版本的Wrangler可能使用这种方式，但 flags 是目前推荐的 